[project]
name = "bitcoin-backed-lending"
authors = []
description = ""
telemetry = true
requirements = []
[contracts.bitcoin-lending]
path = "contracts/bitcoin-lending.clar"
depends_on = ["sip-010-trait", "mock-sbtc", "mock-xusd"]

[contracts.mock-sbtc]
path = "contracts/mock-sbtc.clar"
depends_on = ["sip-010-trait"]

[contracts.mock-xusd]
path = "contracts/mock-xusd.clar"
depends_on = ["sip-010-trait"]

[contracts.sip-010-trait]
path = "contracts/sip-010-trait.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
